CREATE TABLE `{:=DBPREFIX=:}forums` (
  `id` smallint(5) unsigned NOT NULL auto_increment,
  `name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `topics` int(10) unsigned NOT NULL NOT NULL DEFAULT '',
  `replies` int(10) unsigned NOT NULL NOT NULL DEFAULT '',
  `parent` smallint(5) unsigned NOT NULL NOT NULL DEFAULT '',
  `position` smallint(4) NOT NULL NOT NULL DEFAULT '',
  `last_topic` int(10) unsigned NOT NULL NOT NULL DEFAULT '',
  `count_posts` enum('0','1') NOT NULL DEFAULT '1',
  `opt` enum('','re','pw') NOT NULL DEFAULT '',
  `optvalue` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `forumzahl` tinyint(3) unsigned NOT NULL NOT NULL DEFAULT '',
  `topiczahl` tinyint(3) unsigned NOT NULL NOT NULL DEFAULT '',
  `prefix` enum('0','1') NOT NULL NOT NULL DEFAULT '',
  `invisible` enum('0','1','2') NOT NULL NOT NULL DEFAULT '',
  `readonly` enum('0','1') NOT NULL NOT NULL DEFAULT '',
  `reply_notification` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `topic_notification` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `active_topic` enum('0','1') NOT NULL DEFAULT '1',
  `message_active` enum('0','1','2') NOT NULL NOT NULL DEFAULT '',
  `message_title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `message_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `lid` smallint(4) unsigned NOT NULL NOT NULL DEFAULT '',
  `post_order` enum('-1','0','1') NOT NULL DEFAULT '-1',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;