CREATE TABLE `{:=DBPREFIX=:}smileys` (
  `id` smallint(5) unsigned NOT NULL auto_increment,
  `search` varchar(255) NOT NULL default '',
  `replace` text NOT NULL,
  `desc` text NOT NULL,
  `show` enum('0','1') NOT NULL default '0',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  AUTO_INCREMENT=32 ;

INSERT INTO `{:=DBPREFIX=:}smileys` (`id`, `search`, `replace`, `desc`, `show`) VALUES
(1, ':D', '{folder}/biggrin.gif', 'Grinning', '1'),
(2, ':}', '{folder}/cheesy.gif', 'Happy', '1'),
(3, '8-)', '{folder}/cool.gif', 'Cool', '1'),
(4, ':eek:', '{folder}/eek.gif', 'Surprised', '1'),
(5, ':(', '{folder}/frown.gif', 'Disappointed', '1'),
(6, ':lol:', '{folder}/lol.gif', 'Laughing', '1'),
(7, ':love:', '{folder}/love.gif', 'In love', '1'),
(8, ':{', '{folder}/mad.gif', 'Angry', '1'),
(9, ':x', '{folder}/nocomment.gif', 'No comment', '1'),
(10, ':o', '{folder}/redface.gif', 'Embarrassing', '1'),
(11, ':shy:', '{folder}/rotwerd.gif', 'Shy', '1'),
(12, ':)', '{folder}/smile.gif', 'Smiling', '1'),
(13, ':p', '{folder}/tongue.gif', 'Tongue', '1'),
(14, ':\\', '{folder}/undecided.gif', 'Undecided', '1'),
(15, '8)', '{folder}/warsnet.gif', 'Innocent', '1'),
(16, ';)', '{folder}/wink.gif', 'Wink', '1'),
(17, ':crazy:', '{folder}/crazy.gif', 'Crazy', '0'),
(18, ':''(', '{folder}/sad.gif', 'Sad', '1'),
(19, ':]', '{folder}/ego.gif', 'Egoistic', '0'),
(20, ':help:', '{folder}/help.gif', 'Helpless', '0'),
(21, ':angel:', '{folder}/engel.gif', 'Angel', '0'),
(22, '(??)', '{folder}/question.gif', 'Question', '0'),
(23, '(!!)', '{folder}/attention.gif', 'Attention', '0'),
(24, '(ii)', '{folder}/info.gif', 'Information', '0'),
(25, ':mail:', '{folder}/mail.gif', 'E-mail', '0'),
(26, ':search:', '{folder}/search.gif', 'Search', '0'),
(27, ':no:', '{folder}/no.gif', 'No', '0'),
(28, ':idea:', '{folder}/idea.gif', 'Idea', '0'),
(29, ':heart:', '{folder}/heart.gif', 'Heart', '0'),
(30, '8-|', '{folder}/www.gif', 'Have a look-around', '0'),
(31, ':yes:', '{folder}/yes.gif', 'Yes', '0');
