CREATE TABLE `{:=DBPREFIX=:}user` (
  `id` mediumint(7) unsigned NOT NULL auto_increment,
  `name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `pw` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `mail` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `regdate` int(10) unsigned NOT NULL DEFAULT 0,
  `posts` mediumint(7) unsigned NOT NULL DEFAULT 0,
  `fullname` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `hp` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `signature` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `about` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `location` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `gender` enum('','m','w') NOT NULL DEFAULT '',
  `birthday` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0000-00-00',
  `pic` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `lastvisit` int(10) unsigned,
  `timezone` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `groups` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `opt_pmnotify` enum('0','1') NOT NULL DEFAULT '1',
  `opt_hidemail` enum('0','1','2') NOT NULL DEFAULT '2',
  `opt_newsletter` enum('0','1','2') NOT NULL DEFAULT '2',
  `opt_showsig` enum('0','1') NOT NULL DEFAULT '1',
  `template` smallint(5) unsigned NOT NULL DEFAULT 0,
  `language` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `confirm` enum('00','01','10','11') NOT NULL DEFAULT '00',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=MyISAM AUTO_INCREMENT=1 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;